import type { Metadata } from "next";
import { inter, lusitana, lusitanaBold } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${lusitana.variable} ${lusitanaBold.variable}`}
    >
      <body className="font-inter antialiased">{children}</body>
    </html>
  );
}
